name: Java CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Prepare Maven wrapper
        run: |
          chmod +x mvnw
          sed -i 's/\r$//' mvnw

      - name: Build with Maven (wrapper, skip tests)
        run: ./mvnw -B clean verify -DskipTests -DskipITs -DskipIntegrationTests



