name: Java CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # --- New: Node & Angular for the UI step Maven triggers ---
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'   # or '20' LTS

      - name: Install Angular CLI globally
        run: npm i -g @angular/cli@17

      - name: Install UI deps (if UI folder exists)
        working-directory: src/main/UI
        run: |
          if [ -f package.json ]; then
            npm ci
          fi
      # ----------------------------------------------------------

      - name: Build (skip tests)
        run: |
          if [ -f mvnw ]; then
            sed -i 's/\r$//' mvnw || true
            chmod +x mvnw || true
            ./mvnw -B -ntp clean verify -DskipTests
          else
            mvn -B -ntp clean verify -DskipTests
          fi





