name: Java CI

on:
  push:
  pull_request:

# Cancel older runs of the same branch if a new push arrives
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UI_DIR: src/main/UI   # change if your UI lives elsewhere

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven   # Maven cache ✅

      # ---- Frontend only if the UI exists ----
      - name: Set up Node & npm cache (only if UI)
        if: hashFiles('${{ env.UI_DIR }}/package-lock.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm
          cache-dependency-path: ${{ env.UI_DIR }}/package-lock.json

      - name: Install Angular CLI (only if UI)
        if: hashFiles('${{ env.UI_DIR }}/package.json') != ''
        run: npm i -g @angular/cli@17

      - name: Install UI deps (only if UI)
        if: hashFiles('${{ env.UI_DIR }}/package.json') != ''
        working-directory: ${{ env.UI_DIR }}
        run: npm ci --no-audit

      # ---- Build backend ----
      - name: Build (skip tests for speed)
        run: |
          chmod +x mvnw || true
          ./mvnw -B -ntp clean verify -DskipTests

      - name: Upload JAR artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: |
            **/target/*.jar
            !**/*-sources.jar
            !**/*-javadoc.jar






