name: Java CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # Sanity info and prove we're at the repo root
      - name: Show workspace
        run: |
          pwd
          ls -la

      # Normalize the Maven wrapper if it exists (Windows CRLF + exec bit)
      - name: Prepare Maven wrapper
        run: |
          if [ -f mvnw ]; then
            echo "Found mvnw"
            sed -i 's/\r$//' mvnw || true
            chmod +x mvnw || true
            ./mvnw -v
          else
            echo "mvnw not found; will use system Maven"
          fi

      # Build (use wrapper if present; otherwise the runner's Maven)
      - name: Build (skip tests)
        run: |
          if [ -f mvnw ]; then
            ./mvnw -B -ntp clean verify -DskipTests -DskipIT -DskipITs -DskipIntegrationTests
          else
            mvn -B -ntp clean verify -DskipTests -DskipIT -DskipITs -DskipIntegrationTests
          fi




